.emoticon<-function(some_txt){

some_txt = gsub("♥", " EMOTELOVE", some_txt)	
some_txt = gsub("❤", " EMOTELOVE" ,some_txt)
some_txt<- gsub('☺',' EMOTEGOOD ', some_txt)

some_txt = gsub(":]", " EMOTEGOOD ", some_txt)	
some_txt = gsub(":3", " EMOTEGOOD ", some_txt)	
some_txt<- gsub(":-P",' EMOTEJOKE ', some_txt) 
some_txt<- gsub(":p",' EMOTEJOKE ', some_txt)
some_txt<- gsub(':)', ' EMOTEGOOD ', some_txt)
some_txt = gsub(":-)", " EMOTEGOOD ", some_txt)	
some_txt = gsub(":o)", " EMOTEGOOD ", some_txt)	
some_txt = gsub(":]", " EMOTEGOOD ", some_txt)	
some_txt = gsub(":3", " EMOTEGOOD ", some_txt)	
some_txt = gsub(":c)", " EMOTEGOOD ", some_txt)	
some_txt = gsub(":>", " EMOTEGOOD ", some_txt)	
some_txt = gsub("=]", " EMOTEGOOD ", some_txt)	
some_txt = gsub(" 8)", " EMOTEGOOD ", some_txt)	
some_txt = gsub("=)", " EMOTEGOOD ", some_txt)	
some_txt = gsub(":}", " EMOTEGOOD ", some_txt)	
some_txt = gsub(":^)", " EMOTEGOOD ", some_txt)	
some_txt = gsub(":っ)", " EMOTEGOOD ", some_txt)	
some_txt = gsub(":-D", " EMOTEGOOD ", some_txt)	
some_txt = gsub(":D", " EMOTEGOOD ", some_txt)	
some_txt = gsub("8-D", " EMOTEGOOD ", some_txt)	
some_txt = gsub("x-D", " EMOTEGOOD ", some_txt)	
some_txt = gsub("xD", " EMOTEGOOD ", some_txt)	
some_txt = gsub("X-D", " EMOTEGOOD ", some_txt)	
some_txt = gsub("XD", " EMOTEGOOD ", some_txt)	
some_txt = gsub("xd", " EMOTEGOOD ", some_txt)
some_txt = gsub("Xd", " EMOTEGOOD ", some_txt)	
some_txt = gsub("xD", " EMOTEGOOD ", some_txt)	
some_txt = gsub("=-D", " EMOTEGOOD ", some_txt)	
some_txt = gsub("=D", " EMOTEGOOD ", some_txt)	
some_txt = gsub("=-3", " EMOTEGOOD ", some_txt)	
some_txt = gsub("=3", " EMOTEGOOD ", some_txt)	
some_txt = gsub("B^D", " EMOTEGOOD ", some_txt)	
some_txt<- gsub(":')",' EMOTEGOOD ', some_txt) 
some_txt<- gsub(":'-)",' EMOTEGOOD ', some_txt) 
some_txt<- gsub(':(',' EMOTEBAD ', some_txt, fixed=T)
some_txt<- gsub('>:[',' EMOTEBAD ', some_txt, fixed=T)
some_txt<- gsub(':-(',' EMOTEBAD ', some_txt, fixed=T)
some_txt<- gsub(':-c',' EMOTEBAD ', some_txt, fixed=T)
some_txt<- gsub(':c',' EMOTEBAD ', some_txt, fixed=T)
some_txt<- gsub(':-<',' EMOTEBAD ', some_txt, fixed=T)
some_txt<- gsub(':っC',' EMOTEBAD ', some_txt, fixed=T)
some_txt<- gsub(':<',' EMOTEBAD ', some_txt, fixed=T)
some_txt<- gsub(':-[',' EMOTEBAD ', some_txt, fixed=T)
some_txt<- gsub(':[',' EMOTEBAD ', some_txt, fixed=T)
some_txt<- gsub(':{',' EMOTEBAD ', some_txt, fixed=T)
some_txt<- gsub(' QQ ',' EMOTECRY ', some_txt, fixed=T) 
some_txt<- gsub('D:<',' EMOTEBAD ', some_txt, fixed=T) 
some_txt<- gsub('D:',' EMOTEBAD ', some_txt, fixed=T) 
some_txt<- gsub('D8',' EMOTEBAD ', some_txt, fixed=T) 
some_txt<- gsub('D;',' EMOTEBAD ', some_txt, fixed=T) 
some_txt<- gsub('D=',' EMOTEBAD ', some_txt, fixed=T) 
some_txt<- gsub('DX',' EMOTEBAD ', some_txt, fixed=T) 
some_txt<- gsub('v.v',' EMOTEBAD ', some_txt, fixed=T) 
some_txt<- gsub("D-':",' EMOTEBAD ', some_txt, fixed=T) 
some_txt<- gsub(':-|',' EMOTEANGRY ', some_txt, fixed=T)
some_txt<- gsub(':@',' EMOTEANGRY ', some_txt, fixed=T)
some_txt<- gsub(":'-(",'EMOTEBAD', some_txt, fixed=T)
some_txt<- gsub(":'(",'EMOTEBAD', some_txt, fixed=T)
some_txt<- gsub(":*",' EMOTEKISS ', some_txt, fixed=T)
some_txt<- gsub(":^*",' EMOTEKISS ', some_txt, fixed=T)
some_txt<- gsub("( '}{' )",' EMOTEKISS ', some_txt, fixed=T)
some_txt<- gsub(";)",' EMOTEWINK ', some_txt, fixed=T)
some_txt<- gsub(";-)",' EMOTEWINK ', some_txt, fixed=T)
some_txt<- gsub("*-)",' EMOTEWINK ', some_txt, fixed=T)
some_txt<- gsub("*)",' EMOTEWINK ', some_txt, fixed=T)
some_txt<- gsub(";-]",' EMOTEWINK ', some_txt, fixed=T)
some_txt<- gsub(";]",' EMOTEWINK ', some_txt, fixed=T)
some_txt<- gsub(";D",' EMOTEWINK ', some_txt, fixed=T)
some_txt<- gsub(";^)",' EMOTEWINK ', some_txt, fixed=T)
some_txt<- gsub(":-,",' EMOTEGOOD ', some_txt, fixed=T)

some_txt<- gsub(">:P",' EMOTEGOOD ', some_txt, fixed=T)
some_txt<- gsub(" :P ",' EMOTEGOOD ', some_txt, fixed=T)
some_txt<- gsub("X-P",' EMOTEGOOD ', some_txt, fixed=T)
some_txt<- gsub("x-p",' EMOTEGOOD ', some_txt, fixed=T)
some_txt<- gsub("xp",' EMOTEGOOD ', some_txt, fixed=T)
some_txt<- gsub("XP",' EMOTEGOOD ', some_txt, fixed=T) 
some_txt<- gsub("=p",' EMOTEGOOD ', some_txt, fixed=T) 
some_txt<- gsub(":Þ",' EMOTEGOOD ', some_txt, fixed=T) 
some_txt<- gsub(":-Þ",' EMOTEGOOD ', some_txt, fixed=T) 
some_txt<- gsub(":-b",' EMOTEGOOD ', some_txt, fixed=T) 
some_txt<- gsub(" :b ",' EMOTEGOOD ', some_txt, fixed=T) 

some_txt<- gsub(">:\\",' EMOTEBAD ', some_txt, fixed=T) 
some_txt<- gsub(">:/",' EMOTEBAD ', some_txt, fixed=T) 
some_txt<- gsub(":-/",' EMOTEBAD ', some_txt, fixed=T) 
some_txt<- gsub(":-.",' EMOTEBAD ', some_txt, fixed=T) 
 some_txt<- gsub("=/",' EMOTEBAD ', some_txt, fixed=T) 
 some_txt<- gsub("=\\",' EMOTEBAD ', some_txt, fixed=T) 
some_txt<- gsub(":L",' EMOTEBAD ', some_txt, fixed=T) 
some_txt<- gsub("=L",' EMOTEBAD ', some_txt, fixed=T) 
some_txt<- gsub(":S",' EMOTEBAD ', some_txt, fixed=T) 
some_txt<- gsub(">.<",' EMOTEBAD ', some_txt, fixed=T) 
some_txt<- gsub(":-|",' EMOTEBAD ', some_txt, fixed=T) 
some_txt<- gsub(":$",' EMOTEBLUSHING ', some_txt, fixed=T) 	

some_txt<- gsub('o.0',' EMOTESHOCK ', some_txt, fixed=T)
some_txt<- gsub('0.o',' EMOTESHOCK ', some_txt, fixed=T)
some_txt<- gsub('8-0',' EMOTESHOCK ', some_txt, fixed=T)
some_txt<- gsub('O.o',' EMOTESHOCK ', some_txt, fixed=T)
some_txt<- gsub('o.O',' EMOTESHOCK ', some_txt, fixed=T)
some_txt<- gsub('O.O',' EMOTESHOCK ', some_txt, fixed=T)
some_txt<- gsub('O_o',' EMOTESHOCK ', some_txt, fixed=T)
some_txt<- gsub('*o*',' EMOTESHOCK ', some_txt, fixed=T)
some_txt<- gsub('*_*',' EMOTESHOCK ', some_txt, fixed=T)
some_txt<- gsub('u_u',' EMOTESHOCK ', some_txt, fixed=T)
some_txt<- gsub('ù_ù',' EMOTESHOCK ', some_txt, fixed=T)		
some_txt<- gsub('ù___ù',' EMOTESHOCK ', some_txt, fixed=T)		
some_txt<- gsub(':OOOO',' EMOTESHOCK ', some_txt, fixed=T)
some_txt<- gsub('<3',' EMOTELOVE ', some_txt, fixed=T)
some_txt<- gsub('-___-',' EMOTESHAME ', some_txt, fixed=T)	
some_txt<- gsub('-__-',' EMOTESHAME ', some_txt, fixed=T)
some_txt<- gsub('-_-',' EMOTESHAME ', some_txt, fixed=T)

some_txt<- gsub("-.-",' EMOTESHAME ', some_txt, fixed=T)
some_txt<- gsub("-,-",' EMOTESHAME ', some_txt, fixed=T)
some_txt<- gsub(":x",' EMOTESIL ', some_txt, fixed=T) 
some_txt<- gsub(":X",' EMOTESIL ', some_txt, fixed=T)
some_txt<- gsub(":-x",' EMOTESIL ', some_txt, fixed=T)
some_txt<- gsub(":-X",' EMOTESIL  ', some_txt, fixed=T)
some_txt<- gsub(":-#",' EMOTESIL ', some_txt, fixed=T) 
some_txt<- gsub(":#",' EMOTESIL ', some_txt, fixed=T)

some_txt<- gsub("'-'",' EMOTEGOOD ', some_txt, fixed=T)
some_txt<- gsub("O:-)",' EMOTEGOOD ', some_txt, fixed=T) 
some_txt<- gsub("0:-3",' EMOTEGOOD ', some_txt, fixed=T)
some_txt<- gsub("0:3",' EMOTEGOOD ', some_txt, fixed=T)
some_txt<- gsub("0:-)",' EMOTEGOOD ', some_txt, fixed=T)
some_txt<- gsub("0:)",' EMOTEGOOD ', some_txt, fixed=T)
some_txt<- gsub("0;^)",' EMOTEGOOD ', some_txt, fixed=T)
	
some_txt<- gsub(">:)",' EMOTEVIL ', some_txt, fixed=T)	
some_txt<- gsub(">;)",' EMOTEVIL ', some_txt, fixed=T)
some_txt<- gsub("#-)",' EMOTEGOOD ', some_txt, fixed=T) 
some_txt<- gsub("%-)",' EMOTEGOOD ', some_txt, fixed=T)	
some_txt<- gsub("%)",' EMOTEGOOD ', some_txt, fixed=T)	

some_txt<- gsub(":-###..",'EMOTESICK', some_txt, fixed=T)
some_txt<- gsub(":###..",'EMOTESICK', some_txt, fixed=T)
some_txt<- gsub("ಠ_ಠ",' EMOTEDISAPP ', some_txt, fixed=T) 
some_txt<- gsub("ಠ_ರೃ",' EMOTEDISAPP ', some_txt, fixed=T) 

some_txt<- gsub(">.<",' EMOTEBAD ', some_txt, fixed=T) 
some_txt<- gsub("^-^",' EMOTEGOOD ', some_txt, fixed=T) 

some_txt<- gsub("~_~",' EMOTEBAD ', some_txt, fixed=T) 
some_txt<- gsub("^_^",' EMOTEGOOD ', some_txt, fixed=T)		
some_txt<- gsub("^^",' EMOTEGOOD ', some_txt, fixed=T)		
some_txt<- gsub("^_-",' EMOTEGOOD ', some_txt, fixed=T)		
some_txt<- gsub("+_+",' EMOTEGOOD ', some_txt, fixed=T)		
some_txt<- gsub("+o+",' EMOTEGOOD ', some_txt, fixed=T)		

some_txt<- gsub("^O^",' EMOTEGOOD ', some_txt, fixed=T)		
some_txt<- gsub("^o^",' EMOTEGOOD ', some_txt, fixed=T)		
some_txt<- gsub("'_'",' EMOTEBAD ', some_txt, fixed=T)		
some_txt<- gsub("T_T",' EMOTEBAD ', some_txt, fixed=T)		
some_txt<- gsub("ToT",' EMOTEBAD ', some_txt, fixed=T)		
some_txt<- gsub(";_;",' EMOTEBAD ', some_txt, fixed=T)		
some_txt<- gsub("@_@",' EMOTESHOCK ', some_txt, fixed=T)		

}
