normalizzapunteggiatura <-
function(testo){
	
	testo <- paste(" ",testo," ", sep="")
	testo <- gsub("#\\s+", "#", testo, perl=TRUE)
	testo <- gsub("#", " #", testo, perl=TRUE)
	testo <- gsub("@\\s+", "@", testo, perl=TRUE)	
	testo <- gsub("@", " @", testo, perl=TRUE)
	
	testo <- gsub("\n",' ',testo,fixed=TRUE)
	testo <- gsub("\t",' ',testo,fixed=TRUE)
	testo <- gsub("\r",' ',testo,fixed=TRUE)
	
	testo <- gsub("\\s+", " ", testo, perl=TRUE)	
	testo <- gsub('^( ["][@]| [@]| \034[@])',' RT @', testo, perl=TRUE)	
	testo <- gsub("^( ['][@])",' RT @', testo, perl=TRUE)
	testo <- gsub("^( RT: @)",' RT @', testo, perl=TRUE)
	testo <- gsub("^( RT '@)",' RT @', testo, perl=TRUE)			
	
	testo <- gsub('[///]+',' ', testo, perl=TRUE)
	testo <- gsub('[//?]+',' ', testo, perl=TRUE)
	testo <- gsub('[//!]+',' ', testo, perl=TRUE)
	testo <- gsub('[//|]+',' ', testo, perl=TRUE)
	testo <- gsub("'"," ",testo,fixed=TRUE)
	testo <- gsub('"',' ',testo,fixed=TRUE)
	testo <- gsub('”|“|“|”|“',' ',testo)
	testo <- gsub('»|«|«',' ',testo,fixed=TRUE)
	testo <- gsub('`|‘|‘',' ',testo)	
	testo <- gsub('…',' ',testo,fixed=TRUE)	
	testo <- gsub("\\\\"," ",testo)
	testo <- gsub("\\/"," ",testo)
	testo <- gsub("[=]"," ",testo,perl=TRUE)
	testo <- gsub("[+]"," ",testo,perl=TRUE)
	testo <- gsub("[-]"," ",testo,perl=TRUE)
	testo <- gsub('\\*{1}',' ', testo, perl=TRUE)
	testo <- gsub("[<]"," ",testo,perl=TRUE)
	testo <- gsub("[>]"," ",testo,perl=TRUE)
	testo <- gsub("[~]"," ",testo,perl=TRUE)
	testo <- gsub("[\\^]"," ",testo,perl=TRUE)
	testo <- gsub("[,]"," ",testo,perl=TRUE)
	testo <- gsub("[;]"," ",testo,perl=TRUE)
	testo <- gsub("[:]"," ",testo,perl=TRUE)
	testo <- gsub('[\\.]',' ', testo, perl=T)
	testo <- gsub("[&]"," & ",testo,perl=TRUE)
	# parentesi
	testo <- gsub("[(]"," ",testo,perl=TRUE)
	testo <- gsub("[)]"," ",testo,perl=TRUE)
	testo <- gsub("[{]"," ",testo,perl=TRUE)
	testo <- gsub("[}]"," ",testo,perl=TRUE)
	testo <- gsub("[[]"," ",testo,perl=TRUE)
	testo <- gsub("[]]"," ",testo,perl=TRUE)

	testo <- gsub("\\s+", " ", testo, perl=TRUE)
testo
	}
